### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by binaruappuhamy**
*Final css style adjustments to homepage*

 - Summary 🔺 *(CSS style adjustments to support all screens)*

### CODE REVIEW

**Comment by CatherineZM** [comment]
A couple of things:
1. On desktop view, when the screen is semi-small, the last row here became centered somehow: 
Screen Shot 2022-08-07 at 4 39 05 PM
2. In mobile view, the button on the banner is black:
Screen Shot 2022-08-07 at 4 40 11 PM
3. In mobile view, the texts in cards are centered again:
Screen Shot 2022-08-07 at 4 40 40 PM

**Review by CatherineZM — CHANGES_REQUESTED** [review]
See above comments for change request

**Comment by CatherineZM** [comment]
@binaruappuhamy everything else looks good. But there are package dependencies problems failing the security check. Please fix those

**Review by CatherineZM — CHANGES_REQUESTED** [review]
Please resolve denpendencies problem

**Comment by binaruappuhamy** [comment]
when I searched all I could find to solve that issue is to use 
`npm ci --legacy-peer-deps`
instead of 
`npm ci`

I am not really sure what else I can do to fix that, please let me know too if you can find a fix for this.
@CatherineZM

**Pull request merged**
