### PR TITLE
Yicheng Wei Pull Request for Training

### PR DESCRIPTION
**Pull request by davidYichengWei**

### CODE REVIEW

**Review by Felix-Deng — APPROVED** [review]
Well done, David!

**Review by iiiizuo — COMMENTED** [review]
Good job, Yicheng!

**Comment by CatherineZM** [comment]
@davidYichengWei the security check did not pass. Your image variable still needs one more component.

**Review by Felix-Deng — APPROVED** [review]
Hi David, your website looks good! Just a note for the security check, instead of writing `import Card from 'react-bootstrap/Card';`, please write `import {Card} from 'react-bootstrap'`. This is similar for all other imports as well. And just a quick hint for the future, you can even import all components in only one {}, so you only need one line of code instead of five.

**Comment by davidYichengWei** [comment]
@Felix-Deng I was checking this website  https://react-bootstrap.github.io/getting-started/introduction/ and it says we should import individual components for efficiency purpose, so that actually doesn't matter for us?

Also, I saw some checks are failing, do I need to make them all pass?

Screen Shot 2022-02-19 at 7 30 19 PM

**Review by Felix-Deng — APPROVED** [review]
Hi David, regarding your previous comment, it is actually a good observation! Due to differences in the version that we will be using for our future website development, we will actually be using a less optimal coding style. However, since we are not building a huge commercial website, there shouldn't be too much of a concern in terms of efficiency. Your new push looks good! But just remember to also remove (i.e. don't import) components that you have not used in your code, so that you should pass all security checks.

**Comment by CatherineZM** [comment]
Approved. Closing the PR

**Pull request closed without merging**
