### PR TITLE
EventUI: Add sidebar to navigate between upcoming/past events

### PR DESCRIPTION
**Pull request by davidYichengWei**
*Note: 🔺filed are required.*

 - Summary 🔺 
   - Modified font sizes, line heights and font weights to improve readabiulity
   - Added support for photo of event guests
   - Added a link for event registration

 
 - Issue Number 🔺 https://github.com/UofT-VEEP/VEEP-Website/issues/40 

- New Proposal 
  - The original design of the event page was two tabs: Events This Year and Past Events, however, I think using Upcoming Events and Past Events makes more sense, as it makes it easier for people to see what events to expect in the future, and where o look for if they are looking for past events. Do you agree with this change? If so, I think we can remove the Event Replay accordion as well.

### CODE REVIEW

**Comment by CatherineZM** [comment]
> I think using Upcoming Events and Past Events makes more sense, as it makes it easier for people to see what events to expect in the future, and where o look for if they are looking for past events.

@davidYichengWei Good idea! What do you think if we add a tab on the side of the screen (like vertically) that says upcoming events and past events. And then inside past events we can have different years (similar to past projects) I feel like that would look nice. What do you think?

**Comment by davidYichengWei** [comment]
Hi @CatherineZM ,

Yeah, I think that will definitely look good. What I'm thinking is just that if I'm a person who just wants to learn about past events of VEEP, it might be easier for me if all events are displayed on one page sorted by date, than if I have to click on different years to view the past events. Splitting them into different years will definitely make the page more organized as we have more events in the future though. What are your thoughts on this? We can discuss this in the meeting later as well.

**Comment by CatherineZM** [comment]
> it might be easier for me if all events are displayed on one page sorted by date, than if I have to click on different years to view the past events.

@davidYichengWei That's true. We could just have a bigger title of what year the event is and have the list instead of accordion for now. But in the future when we have a lot more events, we can have an accordion instead

**Review by CatherineZM — APPROVED** [review]
Good job!

**Comment by CatherineZM** [comment]
@Felix-Deng @iiiizuo Take a look when you get a chance. If there's no more changes, you can merge it

**Review by Felix-Deng — APPROVED** [review]

**Pull request merged**
