### PR TITLE
EventUI_PastEventTabs: Support navigating to past events in different…

### PR DESCRIPTION
**Pull request by davidYichengWei**
- Summary 🔺 Support navigating to past events in different years by clicking on tabs in the sidebar
 
 - Issue Number 🔺 [*(Paste your issue link here)*](https://github.com/UofT-VEEP/VEEP-Website/issues/40)

### CODE REVIEW

**Comment by iiiizuo** [comment]
-  When in mobile view, side bar is blocked by main content.
Beside that, everything looks great to me! Keep up with the good work.

**Review by iiiizuo — COMMENTED** [review]
- When in mobile view, side bar is blocked by main content.

Beside that, everything looks great to me! Keep up with the good work.

**Review by CatherineZM — CHANGES_REQUESTED** [review]
See Iris' comment above for change request

**Review by Felix-Deng — APPROVED** [review]
This looks good to me. @CatherineZM @iiiizuo can we merge this PR?

**Review by CatherineZM — APPROVED** [review]
Looks good. @Felix-Deng Let's merge

**Pull request merged**
